# Generated by Django 5.1.1 on 2024-12-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('player', models.IntegerField(default=0)),
                ('player1', models.CharField(max_length=255)),
                ('player2', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GamePlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Paddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('player', models.IntegerField(default=0)),
                ('start', models.BooleanField(default=False)),
                ('winner_nb', models.IntegerField(default=0)),
                ('players', models.JSONField(default=list)),
                ('player_len', models.IntegerField(default=0)),
                ('losers', models.JSONField(default=list)),
                ('winners', models.JSONField(default=list)),
                ('stats_id', models.IntegerField(default=-1)),
            ],
        ),
    ]
