# Generated by Django 5.1.1 on 2024-12-11 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='users',
            field=models.ManyToManyField(related_name='gamedata', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentsdata',
            name='users',
            field=models.ManyToManyField(related_name='tournamentsdata', to=settings.AUTH_USER_MODEL),
        ),
    ]
